---
title: "Week 4: R Programming GGPLOT - 50 points (LO1)(LO2)"
author: "guanhua"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
knitr::opts_chunk$set(tidy = TRUE, tidy.opts = list(width.cutoff = 60))
```

[ggplot for plots and graphs. An introduction to data visualization using R programming](https://www.youtube.com/watch?v=HPJn1CMvtmI)

```{r plot}
ggplot(BOD, aes(Time, demand)) +
  geom_point(size = 3) +
  geom_line(color = "red")

CO2 %>%
  ggplot(aes(conc, uptake, color = Treatment)) +
  geom_point(size = 3, alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap(~Type) +
  labs(title = "Concentration of co2") +
  theme_bw()

CO2 %>%
  ggplot(aes(Treatment, uptake)) +
  geom_boxplot() +
  geom_point(alpha = 0.5, aes(size = conc, color = Plant)) +
  facet_wrap(~Type) +
  coord_flip() +
  theme_bw()
  labs(title = "Chilled vs Non-chilled")

mpg %>%
  filter(cty < 25) %>%
  ggplot(aes(displ, cty)) +
  geom_point(aes(color = drv, size = trans), alpha = 0.5) +
  geom_smooth(method = "lm") +
  facet_wrap(~year, nrow = 1) +
  labs(x = "Engine size", y = "MPG in the city", title = "Fuel efficiency") +
  theme_bw()
```
